# Jekyll configuration
title: TFG chatbot
description: Proyecto de Trabajo de Fin de Grado sobre un chatbot educativo con IA
baseurl: "/TFG-Chatbot"
url: "https://GabrielFranciscoSM.github.io"

# Theme - Just the Docs
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: light

# Footer content
footer_content: "Copyright &copy; 2025 Gabriel Francisco Sánchez Muñoz. Distribuido bajo licencia MIT."

# Back to top link
back_to_top: true
back_to_top_text: "Volver arriba"

# GitHub integration
gh_edit_link: true
gh_edit_link_text: "Editar en GitHub"
gh_edit_repository: "https://github.com/GabrielFranciscoSM/TFG-Chatbot"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

# Exclude files from processing
exclude:
  - backend/
  - scripts/
  - tests/
  - models/
  - local/
  - devLog/
  - docker-compose.yml
  - Dockerfile
  - requirements.txt
  - pytest.ini
  - "*.pyc"
  - __pycache__/
