services:
  vllm-openai:
    container_name: my-vllm-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities:
                - gpu
    volumes:
        - "./models:/models"
    env_file:
      - .env 
    environment:
        HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
    ports:
        - 8000:8000
    image: docker.io/vllm/vllm-openai:latest
    command: >
      --model /models/unsloth--mistral-7b-instruct-v0.3-bnb-4bit
      --max-num-seqs 8
      --max-model-len 1000
      --gpu-memory-utilization 0.9
      --port 8000
      --tool-call-parser mistral 
      --chat-template /models/unsloth--mistral-7b-instruct-v0.3-bnb-4bit/tool_chat_template_mistral_parallel.jinja
      --enable-auto-tool-choice
      --quantization bitsandbytes
