services:
  vllm-openai:
    container_name: my-vllm-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities:
                - gpu
    volumes:
        - "./models:/models"
    env_file:
      - .env 
    environment:
        HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
    ports:
        - ${VLLM_MAIN_PORT}:${VLLM_MAIN_PORT}
    image: docker.io/vllm/vllm-openai:latest
    command: >
      --model ${MODEL_PATH}
      --max-num-seqs 8
      --max-model-len 4096
      --gpu-memory-utilization 0.9
      --port ${VLLM_MAIN_PORT}
      --tool-call-parser mistral 
      --chat-template ${MODEL_PATH}/tool_chat_template_mistral_parallel.jinja
      --enable-auto-tool-choice
      --quantization bitsandbytes
