[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tfg-chatbot-gateway"
version = "0.1.0"
description = "Main Backend/Gateway for TFG Chatbot"
authors = [ { name = "Gabriel Francisco" } ]
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "httpx",
  "python-jose[cryptography]",
  "pydantic[email]",
  "pydantic-settings",
  "python-multipart",
  "bcrypt>=5.0.0",
  "pymongo",
  "python-json-logger>=2.0.0",
  "prometheus-fastapi-instrumentator>=7.0.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0",
  "pytest-asyncio>=0.21.0",
  "mongomock",
  "httpx"
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]
