name: Create Release from Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare release notes from CHANGELOG.md
        id: release_notes
        run: |
          TAG=${GITHUB_REF##*/}
          # extract the section for the tag from CHANGELOG.md if present
          awk -v tag="${TAG#v}" 'BEGIN{RS="\n## ";found=0}{if($0 ~ ("^" tag "\\]")){print "## " $0;found=1}} END{if(found==0) print "Release " tag}' CHANGELOG.md > release_notes.txt || echo "Release ${TAG#v}" > release_notes.txt

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ github.ref_name }}
          gh release create "$TAG" \
            --title "Release $TAG" \
            --notes-file release_notes.txt
